### PR TITLE
Bugfix/500 errors

### LINKED ISSUE #13: Socket Hang Up error
Need to investigate what causes this error:
```
Upload failed!
socket hang up
Error: socket hang up
   at createHangUpError (_http_client.js:302:15)
   at TLSSocket.socketOnEnd (_http_client.js:394:23)
   at emitNone (events.js:91:20)
   at TLSSocket.emit (events.js:186:7)
   at endReadableNT (_stream_readable.js:974:12)
   at _combinedTickCallback (internal/process/next_tick.js:74:11)
   at process._tickCallback (internal/process/next_tick.js:98:9)
```

### PR DESCRIPTION
**Pull request by corycaywood**
Resolves #13 

Added incremental retries - each retry will take twice as long as the previous retry.

Added a queue using the "promise-request" module so that no more than 29 connections can be made at once. This has reduced the number of request retries caused by 500 errors.

### CODE REVIEW

**Comment by SwinX** [comment]
> Added a queue using the "promise-request" module so that no more than 29 connections can be made at once. This has reduced the number of request retries caused by 500 errors.

Was it measured somehow?
How much articles and sections were in category you uploaded? Were there any cases when uploading failed with error?

File: lib/zendesk-uploader/client-wrapper.js [hunk 1]
```diff
@@ -1,16 +1,19 @@
...
 const logger = require('../logger');
 
 /**
  * Wrapper class for the `node-zendesk` api client
  * Wraps all requests in the `articles`, `sections`, `categories`, and `accesspolcies` objects in Promises
  * Also wraps requests with a retry functionality that will retry the request if the error response is >= 500 or contains a `retryAfter` property
+ * Subsequent retries without a "retry-after" header will wait twice as long as the last retry before trying the request again
  */
 
 const MAX_RETRIES = 5;
```
Comment (SwinX) [inline lib/zendesk-uploader/client-wrapper.js]: After config would be merged, suggest moving this settings there. #29

File: lib/zendesk-uploader/client-wrapper.js [hunk 2]
```diff
@@ -1,16 +1,19 @@
 const request = require('request');
 const fs = require('fs');
+const Queue = require('promise-queue');
```
Comment (SwinX) [inline lib/zendesk-uploader/client-wrapper.js]: Queue will use native promises by default. Since we're using `bluebird` I guess it might be a good idea not to mix it. Need to call `Queue.configure` somewhere in the beginning of the script.

File: lib/zendesk-uploader/client-wrapper.js [hunk 3]
```diff
@@ -31,7 +35,7 @@ module.exports = class ZendeskClientWrapper {
             this._wrapPrototypeMethods(endpoint);
         });
         // This method must be created manually because the API client doesn't have it
-        this.articleattachments.create = (articleId, resourcePath) => this._createPromiseRequest(this._createAttachment, articleId, resourcePath);
+        this.articleattachments.create = (articleId, resourcePath) => this._queue.add(() => this._createPromiseRequest(this._createAttachment, articleId, resourcePath));
```
Comment (SwinX) [inline lib/zendesk-uploader/client-wrapper.js]: Maybe expand this a bit? 

```javascript
this.articleattachments.create = (articleId, resourcePath) => {
    const request = this._createPromiseRequest(this._createAttachment, articleId, resourcePath);
    
    return this._queue.add(request);
}
```
?

File: lib/zendesk-uploader/client-wrapper.js [hunk 4]
```diff
@@ -51,14 +55,14 @@ module.exports = class ZendeskClientWrapper {
...
             // Passes the method's parent object as `this` value - for example `client.articles`
-            return this._createPromiseRequest.apply(client, args);
+            return this._queue.add(() => this._createPromiseRequest.apply(client, args));
         };
     }
 
-    _createPromiseRequest() {
+    _createPromiseRequest(...args) {
         let retries = MAX_RETRIES;
+        let retryNumber = 0;
```
Comment (SwinX) [inline lib/zendesk-uploader/client-wrapper.js]: Maybe calculate this?
```javascript
retries--;
const retryNumer = MAX_RETRIES - retryNumber;
```

File: lib/zendesk-uploader/client-wrapper.js [hunk 5]
```diff
@@ -68,7 +72,11 @@ module.exports = class ZendeskClientWrapper {
                     // err.retryAfter is present on all 429 (rate limit has been exceeded) and some 503 errors
                     // err.retryAfter is time to wait in seconds
                     retries--;
-                    let retryAfter = err.retryAfter ? err.retryAfter * 1000 : RETRY_AFTER_DEFAULT;
+                    retryNumber++;
+                    const retryAfter = err.retryAfter
+                        ? err.retryAfter * 1000
+                        // Default retry should wait twice as long as the previous retry
+                        : RETRY_AFTER_DEFAULT * Math.max(Math.pow(2, retryNumber - 1), 1);
```
Comment (SwinX) [inline lib/zendesk-uploader/client-wrapper.js]: Why do we subtract 1 from `retryNumber`?
Also, isn't retry time grow to fast? For 6th retry delay would be 16 seconds. Maybe we need to add also max waiting time?

File: package.json [hunk 6]
```diff
@@ -38,7 +38,8 @@
     "lodash": "4.17.4",
     "markdown-it": "8.3.1",
     "markdown-it-github-toc": "3.1.0",
-    "node-zendesk": "1.1.12"
+    "node-zendesk": "1.1.12",
+    "promise-queue": "^2.2.3"
```
Comment (SwinX) [inline package.json]: `^2.2.3` -> `2.2.3`

File: test/unit/zendesk-uploader/client-wrapper.js [hunk 7]
```diff
@@ -146,6 +146,27 @@ describe('ZendeskClientWrapper', () => {
...
+            let clock = sandbox.useFakeTimers();
+            let createArticle = this.zendeskClient.articles.create(123, {});
+
+            expect(stub).to.have.been.calledOnce;
+            clock.tick(500);
+            expect(stub).to.have.been.calledTwice;
+            clock.tick(1000);
+            expect(stub).to.have.been.calledThrice;
+            clock.tick(2000);
+            return createArticle.then(() => {
```
Comment (SwinX) [inline test/unit/zendesk-uploader/client-wrapper.js]: This part looks redundant

File: lib/zendesk-uploader/client-wrapper.js [hunk 8]
```diff
@@ -1,16 +1,19 @@
...
 const fs = require('fs');
+const Queue = require('promise-queue');
 const constants = require('./constants');
 const logger = require('../logger');
 
 /**
  * Wrapper class for the `node-zendesk` api client
  * Wraps all requests in the `articles`, `sections`, `categories`, and `accesspolcies` objects in Promises
  * Also wraps requests with a retry functionality that will retry the request if the error response is >= 500 or contains a `retryAfter` property
+ * Subsequent retries without a "retry-after" header will wait twice as long as the last retry before trying the request again
```
Comment (SwinX) [inline lib/zendesk-uploader/client-wrapper.js:16]: Probably need to add couple of words about queue

**Comment by corycaywood-rak** [comment]
The issue with retries due to 500 errors occurs most often during resource uploads because they maintain a connection for a longer time period. So I tested on a repo with 80 resources. 

Before implementing this solution, the tool would log about 30 retries in a row. Now it logs 10 or less. 

I tested how many connections can be made at once before Zendesk returns a 500 error, and it was around 30 connections, so that's why I chose 29 as `MAX_CONCURRENT`, but this number maybe still needs to be adjusted.

File: lib/zendesk-uploader/client-wrapper.js (hunk 8 above)
Comment (corycaywood-rak) [inline lib/zendesk-uploader/client-wrapper.js]: I've added this in the latest commit.

File: lib/zendesk-uploader/client-wrapper.js (hunk 1 above)
Comment (corycaywood-rak) [inline lib/zendesk-uploader/client-wrapper.js]: That's probably a good idea!

File: lib/zendesk-uploader/client-wrapper.js (hunk 5 above)
Comment (corycaywood-rak) [inline lib/zendesk-uploader/client-wrapper.js]: I've added a `MAX_RETRY_TIME` set to 8000ms. I guess this setting could go in the config as well.

Comment (corycaywood) [reply lib/zendesk-uploader/client-wrapper.js]: I've added a MAX_RETRY_TIME set to 8000ms. I guess this setting could go in the config as well.

**Comment by corycaywood** [comment]
The issue with retries due to 500 errors occurs most often during resource uploads because they maintain a connection for a longer time period. So I tested on a repo with 80 resources.

Before implementing this solution, the tool would log about 30 retries in a row. Now it logs 10 or less.

I tested how many connections can be made at once before Zendesk returns a 500 error, and it was around 30 connections, so that's why I chose 29 as MAX_CONCURRENT, but this number maybe still needs to be adjusted.

File: test/unit/zendesk-uploader/client-wrapper.js [hunk 9]
```diff
@@ -146,13 +146,39 @@ describe('ZendeskClientWrapper', () => {
...
+
+            clock.tick(500 + 1000 + 2000);
+            return createArticle.then(() => {
+                expect(stub.callCount).to.be.equal(4);
+            });
+        });
+
+        it('should not wait longer than 8000ms on subsequent retries due to 500 errors', () => {
+            const stub = sandbox.stub(this.zendeskStub.articles, 'create').yields({statusCode: 503});
+            stub.onCall(6).yields(null, null, {});
```
Comment (SwinX) [inline test/unit/zendesk-uploader/client-wrapper.js:170]: 👍

File: test/unit/zendesk-uploader/client-wrapper.js [hunk 10]
```diff
@@ -146,13 +146,39 @@ describe('ZendeskClientWrapper', () => {
...
+
+            let clock = sandbox.useFakeTimers();
+            let createArticle = this.zendeskClient.articles.create(123, {});
+
+            clock.tick(500 + 1000 + 2000 + 4000 + 8000 + 8000);
+            return createArticle.then(() => {
+                expect(stub.callCount).to.be.equal(7);
```
Comment (SwinX) [inline test/unit/zendesk-uploader/client-wrapper.js]: I'm not sure this is checking what we need. All 7 calls to API may be done in first 500 ms for instance.

File: test/unit/zendesk-uploader/client-wrapper.js [hunk 11]
```diff
@@ -146,13 +146,39 @@ describe('ZendeskClientWrapper', () => {
...
+        it('should retry after twice as long as the last retry for the request when there are subsequent 500 errors', () => {
+            const stub = sandbox.stub(this.zendeskStub.articles, 'create').yields({statusCode: 503});
+            stub.onCall(3).yields(null, null, {});
+
+            let clock = sandbox.useFakeTimers();
+            let createArticle = this.zendeskClient.articles.create(123, {});
+
+            clock.tick(500 + 1000 + 2000);
+            return createArticle.then(() => {
+                expect(stub.callCount).to.be.equal(4);
```
Comment (SwinX) [inline test/unit/zendesk-uploader/client-wrapper.js]: Same here - all calls may happen in first 500 ms, isn't it?

File: test/unit/zendesk-uploader/client-wrapper.js [hunk 12]
```diff
@@ -146,13 +146,48 @@ describe('ZendeskClientWrapper', () => {
...
 
-        it('should reject the promise if the request fails after 5 retries', () => {
+        it('should retry after twice as long as the last retry for the request when there are subsequent 500 errors', () => {
+            const stub = sandbox.stub(this.zendeskStub.articles, 'create').yields({statusCode: 503});
+            stub.onCall(3).yields(null, null, {});
+
+            let clock = sandbox.useFakeTimers();
+            let createArticle = this.zendeskClient.articles.create(123, {});
+
+            clock.tick(500);
```
Comment (SwinX) [inline test/unit/zendesk-uploader/client-wrapper.js:156]: Suggest changing this one to following:

1 - check nothing called.
2 - tick 500, check - 1 call
3 - tick 500, check still 1 call
4 - tick 500 more, check 2 calls
?

File: test/unit/zendesk-uploader/client-wrapper.js [hunk 13]
```diff
@@ -146,13 +146,48 @@ describe('ZendeskClientWrapper', () => {
...
+
+        it('should not wait longer than 8000ms on subsequent retries due to 500 errors', () => {
+            const stub = sandbox.stub(this.zendeskStub.articles, 'create').yields({statusCode: 503});
+            stub.onCall(6).yields(null, null, {});
+
+            let clock = sandbox.useFakeTimers();
+            let createArticle = this.zendeskClient.articles.create(123, {});
+
+            clock.tick(500 + 1000 + 2000 + 4000 + 8000);
+            expect(stub.callCount).to.be.equal(6);
```
Comment (SwinX) [inline test/unit/zendesk-uploader/client-wrapper.js:176]: Same here - maybe check that before 8000 method still not called?

Comment (corycaywood) [reply test/unit/zendesk-uploader/client-wrapper.js:176]: This one is checking that it's called 6 times, then ticking another 8000, then checks that it was called 7 times. I don't think this one needs any extra checks because the test above is already checking that the times are incremented correctly.

**Review by SwinX — APPROVED** [review]
